### ISSUE TITLE
Verify md5/shasum

### ISSUE THREAD

**Issue by mikroskeem** [mikroskeem/PicoMaven#3]
Since one can't always count on internet stability, and downloads might break, then checksum verification would help developers to identify broken dependencies and try downloading them again.

Checksum verification could be configured to fetch checksum from repository and/or to use predefined checksums.

**Comment by BrainStone** [comment]
I would highly apprechiate this feature!

**Comment by mikroskeem** [comment]
Functionality added in 4771e47caf148225c5e501145de3dc253a4186c9, PicoMaven supports SHA-1, MD-5 and SHA-256 (however latter is not attempted to fetch from the repository).

Both hex and base64 encoded hashes are supported, however API is not stable until next release
