### ISSUE TITLE
Convinience method to inject downloaded jars into classpath

### ISSUE THREAD

**Issue by BrainStone** [mikroskeem/PicoMaven#6]
A simple conviniece method to inject all downloaded paths into the classpath would be very useful.

**Comment by mikroskeem** [comment]
I'd rather not add classpath injection feature to PicoMaven, as project's point is only to supply convenient downloading library.

You could look at [Shuriken library](https://github.com/mikroskeem/Shuriken/), which provides [utility class for injecting libraries to system classpath](https://github.com/mikroskeem/Shuriken/blob/master/instrumentation/src/main/java/eu/mikroskeem/shuriken/instrumentation/ClassLoaderTools.java#L68)
