### ISSUE TITLE
Question: Maven repository

### ISSUE THREAD

**Issue by jlerbsc** [mikroskeem/PicoMaven#7]
Does PicoMaven installed on a maven repository? How can we use it on maven project?

**Comment by mikroskeem** [comment]
PicoMaven is deployed currently at [repo.wut.ee](https://repo.wut.ee/repository/mikroskeem-repo).

Example how to use PicoMaven in your project is in [README.md](https://github.com/mikroskeem/PicoMaven/blob/master/README.md) and in [Orion project](https://github.com/OrionMinecraft/Orion/blob/master/OrionLauncher/src/main/java/eu/mikroskeem/orion/launcher/Bootstrap.java#L185).
