### ISSUE TITLE
Document on how to add this your project

### ISSUE THREAD

**Issue by BrainStone** [mikroskeem/PicoMaven#8]
Having the usage in the README is nice, but I am missing the docs on how to add it to my project. In other words the group ID, the project and maven repo.

Would be lovely to put there. (Not that I can't figure it out from the code, but people without gradle experience might not)

**Comment by mikroskeem** [comment]
Will do once I get this project polished enough

**Comment by BrainStone** [comment]
Why not now?

**Comment by mikroskeem** [comment]
I am doing some heavy refactoring right now, so I am going to make some changes to API. There is no point to documentate unstable API :)

Just... few more commits. I think.

**Comment by BrainStone** [comment]
Caaaan you maybe give me an ETA?
I'd love to use this project.

**Comment by mikroskeem** [comment]
I am away (not being able to access computer) until 13th of August. If I get back then I can probably give an ETA.

**Comment by mikroskeem** [comment]
I updated the README with new example, but as I've mentioned before then this project is under heave development. However I'll try to keep it updated as I add/refactor things.
